//! CRC-32 checksum for gzip, ported from libdeflate's crc32.c.
//!
//! Uses PCLMULQDQ-based CRC folding when available (x86_64-v2+),
//! falling back to the slice-by-8 method.

use archmage::prelude::*;

use super::tables::CRC32_SLICE8_TABLE;

/// Compute the CRC-32 checksum of `data`, continuing from `crc`.
///
/// To compute from scratch, pass `crc = 0`. To continue a running
/// checksum, pass the previous return value.
///
/// This matches `libdeflate_crc32` semantics: the internal CRC state
/// is inverted before and after processing.
///
/// ```
/// use zenflate::crc32;
///
/// let checksum = crc32(0, b"Hello");
/// // Continue with more data:
/// let checksum = crc32(checksum, b" World");
/// ```
#[allow(unexpected_cfgs)]
pub fn crc32(crc: u32, data: &[u8]) -> u32 {
    if data.is_empty() {
        return crc;
    }
    !incant!(crc32_impl(!crc, data), [v2])
}

// ---------------------------------------------------------------------------
// PCLMULQDQ CRC-32 folding (x86_64-v2: SSE4.1 + PCLMULQDQ)
// ---------------------------------------------------------------------------
//
// Fold constants: x^N mod G(x) where G is the gzip CRC-32 generator polynomial.
// From libdeflate's crc32_multipliers.h (generated by gen-crc32-consts.py).
//
// For VL=16 (128-bit vectors):
//   mults_8v folds across 8*128 = 1024 bits
//   mults_4v folds across 4*128 = 512 bits
//   mults_2v folds across 2*128 = 256 bits
//   mults_1v folds across 1*128 = 128 bits (same as mults_128b for VL=16)

const CRC32_X1055_MODG: i64 = 0x33fff533;
const CRC32_X991_MODG: i64 = 0x910eeec1;
const CRC32_X543_MODG: i64 = 0x8f352d95;
const CRC32_X479_MODG: i64 = 0x1d9513d7;
const CRC32_X287_MODG: i64 = 0xf1da05aa;
const CRC32_X223_MODG: i64 = 0x81256527;
const CRC32_X159_MODG: i64 = 0xae689191;
const CRC32_X95_MODG: i64 = 0xccaa009e;

const CRC32_BARRETT_1: i64 = 0xb4e5b025f7011641u64 as i64; // floor(x^95 / G(x))
const CRC32_BARRETT_2: i64 = 0x00000001db710641u64 as i64; // G(x)

/// fold128(src, dst, mults) = dst XOR clmul(src_lo, mults_lo) XOR clmul(src_hi, mults_hi)
macro_rules! fold128 {
    ($src:expr, $dst:expr, $mults:expr) => {{
        let src = $src;
        let mults = $mults;
        _mm_xor_si128(
            _mm_xor_si128($dst, _mm_clmulepi64_si128(src, mults, 0x00)),
            _mm_clmulepi64_si128(src, mults, 0x11),
        )
    }};
}

/// Barrett reduction: 128-bit polynomial → 32-bit CRC.
///
/// Matches the kernel's crc-pclmul-template.S with n=32 and LSB_CRC=1.
macro_rules! barrett_reduce {
    ($x0:expr, $mults_128b:expr, $barrett:expr) => {{
        // Fold 128 → 64 bits: multiply low half by x^64 and XOR with high half
        let x0 = _mm_xor_si128(
            _mm_clmulepi64_si128($x0, $mults_128b, 0x10),
            _mm_bsrli_si128::<8>($x0),
        );
        // Barrett reduction: two clmul steps
        let x1 = _mm_clmulepi64_si128(x0, $barrett, 0x00);
        let x1 = _mm_clmulepi64_si128(x1, $barrett, 0x10);
        _mm_extract_epi32::<2>(_mm_xor_si128(x0, x1)) as u32
    }};
}

#[cfg(target_arch = "x86_64")]
#[arcane]
fn crc32_impl_v2(_token: X64V2Token, crc: u32, data: &[u8]) -> u32 {
    use safe_unaligned_simd::x86_64::_mm_loadu_si128;

    let len = data.len();

    // PCLMULQDQ needs at least 16 bytes
    if len < 16 {
        return crc32_slice8(crc, data);
    }

    #[inline(always)]
    fn chunk16(data: &[u8], offset: usize) -> &[u8; 16] {
        data[offset..offset + 16].try_into().unwrap()
    }

    // Multiplier vectors (VL=16)
    let mults_8v = _mm_set_epi64x(CRC32_X991_MODG, CRC32_X1055_MODG);
    let mults_4v = _mm_set_epi64x(CRC32_X479_MODG, CRC32_X543_MODG);
    let mults_2v = _mm_set_epi64x(CRC32_X223_MODG, CRC32_X287_MODG);
    let mults_1v = _mm_set_epi64x(CRC32_X95_MODG, CRC32_X159_MODG);
    let barrett = _mm_set_epi64x(CRC32_BARRETT_2, CRC32_BARRETT_1);

    // Initialize: load first 16 bytes, XOR CRC into low 32 bits
    let mut x0 = _mm_xor_si128(
        _mm_loadu_si128(chunk16(data, 0)),
        _mm_cvtsi32_si128(crc as i32),
    );
    let mut pos = 16;

    if len >= 128 {
        // 8-accumulator path: load 8 vectors (128 bytes)
        let mut v0 = x0;
        let mut v1 = _mm_loadu_si128(chunk16(data, 16));
        let mut v2 = _mm_loadu_si128(chunk16(data, 32));
        let mut v3 = _mm_loadu_si128(chunk16(data, 48));
        let mut v4 = _mm_loadu_si128(chunk16(data, 64));
        let mut v5 = _mm_loadu_si128(chunk16(data, 80));
        let mut v6 = _mm_loadu_si128(chunk16(data, 96));
        let mut v7 = _mm_loadu_si128(chunk16(data, 112));
        pos = 128;

        // Main loop: 128 bytes per iteration (8 vectors × 16 bytes)
        while pos + 128 <= len {
            v0 = fold128!(v0, _mm_loadu_si128(chunk16(data, pos)), mults_8v);
            v1 = fold128!(v1, _mm_loadu_si128(chunk16(data, pos + 16)), mults_8v);
            v2 = fold128!(v2, _mm_loadu_si128(chunk16(data, pos + 32)), mults_8v);
            v3 = fold128!(v3, _mm_loadu_si128(chunk16(data, pos + 48)), mults_8v);
            v4 = fold128!(v4, _mm_loadu_si128(chunk16(data, pos + 64)), mults_8v);
            v5 = fold128!(v5, _mm_loadu_si128(chunk16(data, pos + 80)), mults_8v);
            v6 = fold128!(v6, _mm_loadu_si128(chunk16(data, pos + 96)), mults_8v);
            v7 = fold128!(v7, _mm_loadu_si128(chunk16(data, pos + 112)), mults_8v);
            pos += 128;
        }

        // Fold 8 → 4 accumulators
        v0 = fold128!(v0, v4, mults_4v);
        v1 = fold128!(v1, v5, mults_4v);
        v2 = fold128!(v2, v6, mults_4v);
        v3 = fold128!(v3, v7, mults_4v);
        if pos + 64 <= len {
            v0 = fold128!(v0, _mm_loadu_si128(chunk16(data, pos)), mults_4v);
            v1 = fold128!(v1, _mm_loadu_si128(chunk16(data, pos + 16)), mults_4v);
            v2 = fold128!(v2, _mm_loadu_si128(chunk16(data, pos + 32)), mults_4v);
            v3 = fold128!(v3, _mm_loadu_si128(chunk16(data, pos + 48)), mults_4v);
            pos += 64;
        }

        // Fold 4 → 2 accumulators
        v0 = fold128!(v0, v2, mults_2v);
        v1 = fold128!(v1, v3, mults_2v);
        if pos + 32 <= len {
            v0 = fold128!(v0, _mm_loadu_si128(chunk16(data, pos)), mults_2v);
            v1 = fold128!(v1, _mm_loadu_si128(chunk16(data, pos + 16)), mults_2v);
            pos += 32;
        }

        // Fold 2 → 1 accumulator
        x0 = fold128!(v0, v1, mults_1v);
        if pos + 16 <= len {
            x0 = fold128!(x0, _mm_loadu_si128(chunk16(data, pos)), mults_1v);
            pos += 16;
        }
    } else {
        // Small path: fold 16-byte chunks one at a time
        while pos + 16 <= len {
            x0 = fold128!(x0, _mm_loadu_si128(chunk16(data, pos)), mults_1v);
            pos += 16;
        }
    }

    // Handle remaining 1-15 bytes with scalar
    let tail = len - pos;
    if tail > 0 {
        let partial = barrett_reduce!(x0, mults_1v, barrett);
        return crc32_slice8(partial, &data[pos..]);
    }

    // Barrett reduction: 128-bit → 32-bit CRC
    barrett_reduce!(x0, mults_1v, barrett)
}

// ---------------------------------------------------------------------------
// Scalar fallback: slice-by-8
// ---------------------------------------------------------------------------

fn crc32_impl_scalar(_token: ScalarToken, crc: u32, data: &[u8]) -> u32 {
    crc32_slice8(crc, data)
}

/// Core slice-by-8 CRC-32 implementation.
///
/// Processes data in 8-byte chunks using 8 parallel table lookups,
/// with byte-at-a-time processing for the remainder.
fn crc32_slice8(mut crc: u32, data: &[u8]) -> u32 {
    let table = &CRC32_SLICE8_TABLE;

    // Process leading bytes to make the remainder a multiple of 8
    let lead = data.len() % 8;
    for &b in &data[..lead] {
        crc = (crc >> 8) ^ table[((crc as u8) ^ b) as usize];
    }

    // Main loop: 8 bytes at a time via chunks_exact
    for chunk in data[lead..].chunks_exact(8) {
        let v1 = u32::from_le_bytes([chunk[0], chunk[1], chunk[2], chunk[3]]);
        let v2 = u32::from_le_bytes([chunk[4], chunk[5], chunk[6], chunk[7]]);

        #[allow(clippy::identity_op)]
        {
            crc = table[0x700 + ((crc ^ v1) as u8) as usize]
                ^ table[0x600 + (((crc ^ v1) >> 8) as u8) as usize]
                ^ table[0x500 + (((crc ^ v1) >> 16) as u8) as usize]
                ^ table[0x400 + (((crc ^ v1) >> 24) as u8) as usize]
                ^ table[0x300 + (v2 as u8) as usize]
                ^ table[0x200 + ((v2 >> 8) as u8) as usize]
                ^ table[0x100 + ((v2 >> 16) as u8) as usize]
                ^ table[0x000 + ((v2 >> 24) as u8) as usize];
        }
    }

    crc
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_initial_value() {
        assert_eq!(crc32(0, &[]), 0);
    }

    #[test]
    fn test_known_value() {
        // CRC-32 of "123456789" is 0xCBF43926
        assert_eq!(crc32(0, b"123456789"), 0xCBF43926);
    }

    #[test]
    fn test_incremental() {
        let data = b"Hello World";
        let full = crc32(0, data);
        let partial = crc32(0, &data[..5]);
        let incremental = crc32(partial, &data[5..]);
        assert_eq!(full, incremental);
    }
}

#[cfg(test)]
mod parity {
    use super::*;

    fn check_parity(data: &[u8]) {
        let ours = crc32(0, data);
        let theirs = libdeflater::crc32(data);
        assert_eq!(ours, theirs, "crc32 mismatch for {} bytes", data.len());
    }

    fn check_parity_incremental(data: &[u8], split: usize) {
        let split = split.min(data.len());
        let ours = {
            let c = crc32(0, &data[..split]);
            crc32(c, &data[split..])
        };
        let theirs = libdeflater::crc32(data);
        assert_eq!(
            ours,
            theirs,
            "incremental crc32 mismatch for {} bytes split at {}",
            data.len(),
            split
        );
    }

    #[test]
    fn parity_empty() {
        check_parity(&[]);
    }

    #[test]
    fn parity_single_byte() {
        for b in 0..=255u8 {
            check_parity(&[b]);
        }
    }

    #[test]
    fn parity_all_zeros() {
        for &len in &[1, 100, 8, 16, 64, 65536] {
            check_parity(&vec![0u8; len]);
        }
    }

    #[test]
    fn parity_all_ff() {
        for &len in &[1, 100, 8, 16, 64, 65536] {
            check_parity(&vec![0xFFu8; len]);
        }
    }

    #[test]
    fn parity_sequential() {
        let data: Vec<u8> = (0..=255).cycle().take(100_000).collect();
        check_parity(&data);
    }

    #[test]
    fn parity_alignment_variants() {
        // Test SIMD boundary alignment: different leading byte counts before 16-byte chunks
        for offset in 0..32 {
            let data: Vec<u8> = (0..=255).cycle().take(1000 + offset).collect();
            check_parity(&data);
        }
    }

    #[test]
    fn parity_incremental() {
        let data: Vec<u8> = (0..=255).cycle().take(20_000).collect();
        for &split in &[0, 1, 7, 8, 9, 15, 16, 17, 100, 127, 128, 129, 10000, 20000] {
            check_parity_incremental(&data, split);
        }
    }

    #[test]
    fn parity_large() {
        let data: Vec<u8> = (0..=255).cycle().take(1_000_000).collect();
        check_parity(&data);
    }

    #[test]
    fn parity_simd_boundaries() {
        // Test lengths around SIMD thresholds: 16, 32, 64, 128, 256
        for len in (0..300).chain([512, 1024, 4096, 65536].iter().copied()) {
            let data: Vec<u8> = (0..=255).cycle().take(len).collect();
            check_parity(&data);
        }
    }

    /// Verify that PCLMULQDQ (_mm_clmulepi64_si128) compiles as safe inside #[arcane] with V2.
    #[test]
    #[cfg(target_arch = "x86_64")]
    fn pclmulqdq_compiles_in_arcane() {
        use archmage::prelude::*;

        #[arcane]
        fn clmul_test(_token: X64V2Token, a: u64, b: u64) -> u64 {
            let va = _mm_set_epi64x(0, a as i64);
            let vb = _mm_set_epi64x(0, b as i64);
            let result = _mm_clmulepi64_si128(va, vb, 0x00);
            _mm_extract_epi64(result, 0) as u64
        }

        let token = X64V2Token::summon().expect("X64V2 should be available");
        let result = clmul_test(token, 7, 3);
        // 7 clmul 3 in GF(2): (x²+x+1)(x+1) = x³+1 = 9
        assert_eq!(result, 9);
    }
}
